# Generated by Django 5.2.12 on 2026-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alertsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='petlocation',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
