# Generated by Django 5.1.5 on 2025-03-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_pet_animal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
