# Generated by Django 5.1.5 on 2025-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_pet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal_id',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
