# Generated by Django 5.1.5 on 2025-03-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_pet_animal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_location', models.CharField(max_length=200)),
                ('last_seen_date', models.DateField()),
                ('contact_info', models.CharField(max_length=100)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.pet')),
            ],
        ),
    ]
