# Generated by Django 5.1.5 on 2025-03-31 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reporter_name', models.CharField(max_length=100)),
                ('owner_share_info', models.BooleanField(default=False)),
                ('reporter_share_info', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.petlocation')),
            ],
        ),
    ]
