"""
Django settings for animal project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Register PyMySQL as MySQLdb so Django's mysql backend can use it
import pymysql
pymysql.install_as_MySQLdb()

load_dotenv()

HUGGINGFACE_API_TOKEN = os.getenv("HUGGINGFACE_API_TOKEN")

BASE_DIR = Path(__file__).resolve().parent.parent

# Database: TiDB Cloud (MySQL-compatible)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': os.getenv('TIDB_HOST'),
        'PORT': os.getenv('TIDB_PORT', '4000'),
        'USER': os.getenv('TIDB_USERNAME'),
        'PASSWORD': os.getenv('TIDB_PASSWORD'),
        'NAME': os.getenv('TIDB_DATABASE'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'ssl': {'ssl-mode': 'VERIFY_IDENTITY'},
        },
    }
}

# Cloudflare R2 (S3-compatible) storage
AWS_ACCESS_KEY_ID = os.getenv('CLOUDFLARE_R2_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('CLOUDFLARE_R2_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('CLOUDFLARE_BUCKET_NAME', 'pawgle')
# CLOUDFLARE_S3_API is the bucket-scoped endpoint; strip the bucket suffix for boto3
_r2_endpoint = os.getenv('CLOUDFLARE_S3_API', '')
if _r2_endpoint.endswith(f"/{AWS_STORAGE_BUCKET_NAME}"):
    _r2_endpoint = _r2_endpoint[: -(len(AWS_STORAGE_BUCKET_NAME) + 1)]
AWS_S3_ENDPOINT_URL = _r2_endpoint
AWS_S3_REGION_NAME = 'auto'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
# Optional public URL (r2.dev or custom domain). If unset, signed URLs are returned.
R2_PUBLIC_URL = os.getenv('R2_PUBLIC_URL', '')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&ydm2wfh15zep(gm1d^ux_$vi04#p00)2ef(_ip5$htzm=mdd4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# File Storage Configuration - Cloudflare R2
DEFAULT_FILE_STORAGE = 'accounts.storage.R2Storage'

# Media URL points at the public R2 base if configured; otherwise S3Boto3Storage signs URLs
MEDIA_URL = (R2_PUBLIC_URL.rstrip('/') + '/') if R2_PUBLIC_URL else f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/'

# Email configuration - using Resend HTTP API
EMAIL_BACKEND = 'accounts.email_backend.ResendEmailBackend'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'PawGle <onboarding@resend.dev>')
REPLIES_EMAIL = os.getenv('REPLIES_EMAIL', 'PawGle Replies <replies@neokit.app>')
FORWARD_REPLY_SECRET = os.getenv('FORWARD_REPLY_SECRET', '')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_q',
]

Q_CLUSTER = {
    'name': 'pawgle',
    'workers': 1,
    'recycle': 50,
    'timeout': 180,
    'retry': 300,
    'orm': 'default',
    'bulk': 10,
    'queue_limit': 50,
    'catch_up': False,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'animal.urls'

SITE_URL = 'https://pawgle.neokit.app'  # Replace with your actual site URL

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'animal.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_field = 'django.db.models.BigAutoField'

# Logging configuration for debugging storage issues
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'accounts.storage': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}